# Generated by Django 5.0 on 2024-10-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_categoria_blog_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
